### ISSUE TITLE
Scope of this include

### ISSUE THREAD

**Issue by Y-Less** [karimcambridge/SAMP-foreach#10]
Hi,

Firstly, thanks for adding me to the repository (somewht out of the blue - I was not expecting that at all), and thanks for maintaining this (working on two subtly different ones was a pain, and frequently resulted in regressions or bugs in one but not the other).

Anyway, as you added me here, I'm wondering where you are taking this version?  y_iterate has moved on a lot since this version was forked.  A lot of the changes probably can't be back-ported easilly as they would introduce huge extra dependencies (especially the new `yield` keyword); however, the other one is now very well tested, so I was wondering how much of that newer stuff you wanted to pull in, and how much you wanted me for that?

**Comment by karimcambridge** [comment]
Okay, first to start it all off let me explain it from a user based background. Most people were always kind of lost with foreach, it had so many different conflicting versions. I couldn't even understand the versioning properly. So I had this version that always used to work properly because every time i updated I encountered bugs.

So basically the point of this version obviously is to provide that lightweight option without YSI for users who want a quick include and an improvement in speed obviously, if they want more they can use YSI.

I want this version to stay that lightweight option and for you to just overlook the maintenance to make sure I don't mess it up. I just want it bug free and as fast as possible. Uh, if there is any suggestions or obvious bugs you see, if you can fix them.. I don't know of anymore bugs right now, but just incase I can quick mention you and you can check it.

Kinda getting redundant there /:. Anyway. For this version, I was thinking of improving multi iter support (I think they lack alot here) and readding iter_ first, last, begin, next and prev.

**Comment by Y-Less** [comment]
Might I suggest looking in to testing as well?  YSI has a lot of tests for a lot of different foreach cases.  While that would require YSI (or a lot of copying), users wouldn't need that, it would just check correctness and compatability.  Obviously some would need disabling, but the optional compilation could actually be built in to YSI if you wanted.

**Comment by karimcambridge** [comment]
Yes, testing also. Well if it the optional compilation doesn't make us include any other parts of YSI then sure!

**Comment by Y-Less** [comment]
Well I mean put the testing in a mode Well you would need to include parts like y_testing, but you could do that in a stand-alone mode used solely for testing, without requiring it in the include itself. Thus no end-users would need it, but you can still reuse the existing tests.

**Comment by ziggi** [comment]
Also thanks for the invitation but I have my own version of foreach (https://github.com/Open-GTO/foreach). I made this because I wanted to add some features without saving compatibility. And I don't know how I can help you with this version of the library.

**Comment by Y-Less** [comment]
Hmm, I've never seen that fork before, which is odd, because I'm sure I've looked through your profile before...  You've got some nice features - I might have to integrate some of them (if you don't mind).

**Comment by Y-Less** [comment]
One big thing you might want to consider adding is my improved internal format.  It still uses a linked list internally, but unused slots now point to the previous used item + 1 (which may be themselves).  This means that for element X, the previous element is `slot[X - 1] - 1` - for ANY element, both those in the iterator and those not (plus some modulo bounds checks).  Note that this doesn't work for multi iterators.

The net result is that you can now move backwards through the iterator in constant time with no additional memory requirements.  This makes `Iter_Add`, `Iter_Remove`, `Iter_Previous` and more constant time, instead of having their own internal loops.

Edit: OK, `Iter_Add` is apparently still not `O(1)` (not sure why), but `Iter_Remove` is, as shown here: 

https://github.com/Open-GTO/foreach/issues/5

**Comment by ziggi** [comment]
@Y_Less you definetly saw my fork before: https://github.com/Open-GTO/foreach/issues/2
And thanks for suggestion.

**Comment by Y-Less** [comment]
I thought it was slightly surprising that it had passed me by, considering how closely I follow both certain people and YSI forks...  Clearly I'm just an idiot and forgot!

**Comment by karimcambridge** [comment]
Well the decision so far is to keep both this as MANY people still use it. ziggi's is a great expansion tho. Could look into getting people to switch over to that.
